name: Test

on: [push]

jobs:
  test-php-7:
    runs-on: ubuntu-latest
    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}
    strategy:
      fail-fast: false
      matrix:
        php: [7.3, 7.4, 8.0, 8.1]
        laravel: [6.*, 7.*, 8.*, 9.*]
        dependency-version: [prefer-lowest, prefer-stable]
        include:
          - laravel: 6.*
            testbench: 4.*
          - laravel: 7.*
            testbench: 5.*
          - laravel: 8.*
            testbench: 6.*
          - laravel: 9.*
            testbench: 7.*
        exclude:
          - laravel: 6.*
            php: 8.1
          - laravel: 7.*
            php: 8.1
          - laravel: 9.*
            php: 7.3
          - laravel: 9.*
            php: 7.4
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.composer/cache/files
        key: dependencies-${{ matrix.dependency-version }}-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

    - name: Install dependencies
      run: |
        composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
        composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

    - name: Execute tests
      run: vendor/bin/phpunit --coverage-text
